Replace custom commands with @10up/cypress-wp-utils
10up/simple-podcasting pull request #162
Opened 2022-04-05 15:12 UTC by dinhtungdu

### Description of the Change
This PR updates the Cypress test suite to use `@10up/cypress-wp-utils` instead of custom commands. This is currently blocked by https://github.com/10up/cypress-wp-utils/pull/51.

Closes #161

### Verification Process
See tests pass on both local and GH Actions.

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

> Changed - Replaced custom commands with @10up/cypress-wp-utils in end-to-end tests

### Credits

Props @dinhtungdu

2022-04-12 12:00 UTC, cadic requested changes
@dinhtungdu thank you for this great update!

I left couple questions about other commands we can potentially replace.

2022-04-12 12:00 UTC, cadic commented on tests/cypress/integration/admin.test.js
> +		cy.visit('/wp-admin/plugins.php');
Could we use `cy.activatePlugin()` and `cy.deactivatePlugin()` here?

2022-04-12 12:00 UTC, cadic commented on tests/cypress/integration/taxonomy.test.js
> +		cy.visit(
Could we shortcut this with `cy.deleteAllTerms('podcasting_podcasts')`?

2022-04-13 02:40 UTC, dinhtungdu commented
@cadic Thanks for the review. I updated the PR per your suggestion. Please take another look!

2022-04-13 05:51 UTC, cadic approved these changes
LGTM, thank you @dinhtungdu!

2022-04-13 15:34 UTC, merged