feat/40: Add onboarding wizard
10up/simple-podcasting pull request #193
Opened 2022-10-30 10:07 UTC by Sidsector9

Closes #40 

### Verification Process

1. Delete all podcasts from the local setup
2. Deactivate the plugin
3. Activate the plugin
4. Observe the setup wizard

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

### Credits

Props @helen @jeffpaul @Nicolas-knight @jnetek @Sidsector9

2022-11-01 11:27 UTC, cadic requested changes
@Sidsector9 thank you for this change, waiting since 2018 🔥

I left a few comments. Also, using SVG with embedded PNG image doesn't look like a good option to me.

2022-11-01 11:27 UTC, cadic commented on includes/admin/onboarding.php
> +	if ( empty( $podcast_name ) || empty( $podcast_category ) ) {
In case browser form validation is not available or disabled, could we add an error reporting back to the form page?

2022-11-01 11:27 UTC, cadic commented on includes/admin/onboarding.php
> +	if ( is_wp_error( $result ) ) {
Indicating what was going wrong can help users here.

2022-11-01 11:27 UTC, cadic commented on simple-podcasting.php
> +			PODCASTING_VERSION
`$in_footer` argument is imssing

2022-11-08 09:23 UTC, cadic commented
Updated the image from SVG to PNG, added E2E tests for onboarding.

2022-11-08 09:24 UTC, cadic approved these changes, later dismissed

2022-11-08 09:25 UTC, cadic commented
@iamdharmesh asking for additional review because I've added a few changes myself

2022-11-11 14:38 UTC, iamdharmesh requested changes
Thanks for the PR @Sidsector9, Code looks good to me just a minor fix needed to handle the cover image design issue (see screenshot). 

![Screenshot 2022-11-11 at 7 58 08 PM](https://user-images.githubusercontent.com/10613171/201362222-e7cd9fd1-c081-46fc-90b8-0f00310f9dee.png)


Thanks.

2022-11-25 09:47 UTC, iamdharmesh approved these changes
Thanks for great work @Sidsector9. LGTM 🚀

2022-11-30 17:59 UTC, merged