Clean up NPM dependencies and update node to v20
10up/simple-podcasting pull request #275
Opened 2024-02-05 02:58 UTC by Sidsector9

### Description of the Change

This PR cleans up NPM dependencies and updates the node version to `20.11.0`
Closes #274

### Changelog Entry

> Changed - Clean up NPM dependencies and update node to v20

### Credits

Props @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-02-11 23:36 UTC, peterwilsoncc requested changes
The E2E Build workflow is logging a node 16 deprecation error, it would be good to update while working on node fixes.

The E2E tests are failing in the WP Minimum tests. The same is happening on trunk so I suspect this expected due to a class change on the snackbar component. It's looking for `.components-snackbar`.

Other notes:

* `npm run build` works successfully
* wp-env: starts, stops and destroy work as expected
* cypress: runs locally and in e2e workflows

I'm on OS this week so can have a look at the merge conflicts and workflows.

2024-02-11 23:36 UTC, peterwilsoncc commented on package-lock.json
The lock file contains several merge conflict artifacts.

2024-02-11 23:36 UTC, peterwilsoncc commented on webpack.config.js
> +	}
This isn't required as it's handled by the `@wordpress/dependency-extraction-webpack-plugin` in wp-scripts.

2024-02-12 03:38 UTC, peterwilsoncc commented
@jeffpaul I've bumped a bunch of actions to avoid Node deprecation warnings. In some cases I couldn't as they are using other repos that either define an out of date node version.

It looks like the upload-artifact/download-artifact versions will need to be updated in sync across all our repos as v3 uploads are incompatible with v4 downloads.

2024-05-13 17:57 UTC, jeffpaul commented
@peterwilsoncc is this PR otherwise approved to merge?

2024-05-13 23:36 UTC, peterwilsoncc approved these changes
@jeffpaul Yep, otherwise looks good.

2024-05-14 13:59 UTC, merged